### ISSUE TITLE
Running interpreter

### ISSUE THREAD

**Issue by ghost** [rtoal/postfix#1]
Running interpreter produces the following error:

python postfix '((mul sub) (1 nget mul) 4 nget swap exec swap exec)' -10 2
Traceback (most recent call last):
  File "postfix.py", line 4, in <module>
    from interpreter import run
  File "C:\Users\Nedim\Desktop\postfix-master\interpreter.py", line 4, in <module>
    from parser import parse_program
ImportError: cannot import name 'parse_program' from 'parser' (unknown location)

Python version: 3.7
OS: Windows 10 1803

**Comment by rtoal** [comment]
Thanks for this. While it "worked for me," I removed the top-level `__init__.py` file which may have caused the problem on your end. Thanks so much for the issue. Let me know if it works and I'll close if it does.

**Comment by ghost** [comment]
Unfortunately it doesn't work for me, even when __init__.py is removed.

**Comment by rtoal** [comment]
Sorry to hear that.... Likely an environment problem, I really don't know. I see you sucessfully imported `interpreter.py` which is a file in the same folder, but then you could not import `parser.py`. Perhaps you pip installed a parser library and that is interfering? I don't know much about Windows, but maybe you have some environment variable called `PYTHONPATH` or something which is trying to hit some other parser library? I'd recommend making a virtualenv; that should avoid the problem of trying to read the wrong "parser" library (if that is even the problem).
